// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhkph7sS9C3Z6czjdJJfgHjFiwzgekEoo',
    appId: '1:450903924397:web:ab32f4be03545828b6b024',
    messagingSenderId: '450903924397',
    projectId: 'weather-app-e40b4',
    authDomain: 'weather-app-e40b4.firebaseapp.com',
    databaseURL: 'https://weather-app-e40b4-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-e40b4.firebasestorage.app',
    measurementId: 'G-S9JNEN5PW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHFPoQKQc9nQqtClsoDiPtDBlA9hj2fqA',
    appId: '1:450903924397:android:d8ef7ac67e3a5b95b6b024',
    messagingSenderId: '450903924397',
    projectId: 'weather-app-e40b4',
    databaseURL: 'https://weather-app-e40b4-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-e40b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB98c1a3DqzvoMXQFBZpGTwNdesayI9NEs',
    appId: '1:450903924397:ios:84195e3723527b5db6b024',
    messagingSenderId: '450903924397',
    projectId: 'weather-app-e40b4',
    databaseURL: 'https://weather-app-e40b4-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-e40b4.firebasestorage.app',
    iosBundleId: 'com.example.hydromet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB98c1a3DqzvoMXQFBZpGTwNdesayI9NEs',
    appId: '1:450903924397:ios:84195e3723527b5db6b024',
    messagingSenderId: '450903924397',
    projectId: 'weather-app-e40b4',
    databaseURL: 'https://weather-app-e40b4-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-e40b4.firebasestorage.app',
    iosBundleId: 'com.example.hydromet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhkph7sS9C3Z6czjdJJfgHjFiwzgekEoo',
    appId: '1:450903924397:web:628650b849d9d17fb6b024',
    messagingSenderId: '450903924397',
    projectId: 'weather-app-e40b4',
    authDomain: 'weather-app-e40b4.firebaseapp.com',
    databaseURL: 'https://weather-app-e40b4-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-e40b4.firebasestorage.app',
    measurementId: 'G-HBDSYXLYTH',
  );

}